# fly.toml app configuration file generated for silent-shape-527 on 2023-10-18T22:48:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-shape-527"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
