POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "EP 127: Maddie",
    "author": "Jack Rhysider",
    "url": "https://darknetdiaries.com/episode/127/",
    "likes": "0"
}